apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/part-of: n8n-platform

resources:
  - namespace.yaml
  - storageclass.yaml
  - postgres/
  - n8n/