apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - n8n-config.yaml
  - n8n-pvc.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress.yaml
  - n8n-secret.yaml

replacements:
  - source:
      kind: ConfigMap
      name: n8n-config
      fieldPath: data.certificate-arn
    targets:
      - select:
          kind: Ingress
          name: n8n-ingress
        fieldPaths:
          - metadata.annotations.alb\.ingress\.kubernetes\.io/certificate-arn