apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
type: Opaque
stringData:
  # These values will be replaced by environment-specific values
  N8N_ENCRYPTION_KEY: "${N8N_ENCRYPTION_KEY}"
  N8N_BASIC_AUTH_USER: "${N8N_BASIC_AUTH_USER}"
  N8N_BASIC_AUTH_PASSWORD: "${N8N_BASIC_AUTH_PASSWORD}"