apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  # Main postgres admin user
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "change-this-postgres-admin-password"
  POSTGRES_DB: n8n
  
  # Application-specific user (used by n8n)
  POSTGRES_NON_ROOT_USER: n8n
  POSTGRES_NON_ROOT_PASSWORD: "change-this-n8n-user-password"