apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    service: postgres-n8n
  name: postgres-service
  namespace: n8n
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
    service: postgres-n8n